import { useState } from 'react';
import { useNavigate } from 'react-router-dom';

export default function Landing() {
  const navigate = useNavigate();
  const [showStudentModal, setShowStudentModal] = useState(false);
  const [showAccountModal, setShowAccountModal] = useState(false);
  const [activeFaq, setActiveFaq] = useState<number | null>(null);

  const toggleFaq = (index: number) => {
    setActiveFaq(activeFaq === index ? null : index);
  };

  const faqs = [
    {
      q: 'How do student groups register?',
      a: 'Students register using a secure registration link generated by their instructor (e.g., /register?token=...). Direct registration without a token is disabled for safety.',
    },
    {
      q: 'How do I get an Instructor or Panel account?',
      a: 'All Instructor and Panel credentials are provisioned by the system administrator. To request access, please contact us at garciajerico217@gmail.com.',
    },
    {
      q: 'Can panel judges modify grades after submission?',
      a: 'Yes — panel judges can still go back and update their submitted scores at any time, as long as the instructor has not activated the Global Grading Lock. Once an instructor locks grading, all score modifications are frozen across the entire platform.',
    },
    {
      q: 'Does it support offline grading?',
      a: 'Yes, EvalSys auto-saves active grading sessions locally in the browser. Instructors can also print offline grading worksheets if network connections are lost.',
    },
  ];

  return (
    <div className="min-h-screen bg-bg text-text font-sans flex flex-col selection:bg-primary/20">
      {/* ── DESIGNER HEADER ── */}
      <header className="bg-dark text-white border-b border-white/5 sticky top-0 z-40">
        <div className="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <div className="w-10 h-10 rounded-xl bg-primary flex items-center justify-center text-white text-lg font-black shrink-0 shadow-lg shadow-primary/20">
              E
            </div>
            <div>
              <div className="flex items-center gap-2">
                <span className="text-sm font-black tracking-tight uppercase">EvalSys</span>
                <span className="text-[9px] font-mono bg-primary/25 text-primary px-1.5 py-0.5 rounded uppercase tracking-wider font-semibold">
                  v2.0
                </span>
              </div>
              <p className="text-[10px] text-white/40 uppercase tracking-widest font-bold font-mono">
                Automated Evaluation System
              </p>
            </div>
          </div>

          <div className="flex items-center gap-6">
            <span className="hidden md:flex items-center gap-2 text-[10px] font-mono text-white/50 tracking-wider">
              <span className="w-1.5 h-1.5 rounded-full bg-success animate-ping" />
              SYSTEM OPERATIONAL
            </span>
            <button
              onClick={() => navigate('/login')}
              className="bg-primary hover:bg-blue-700 text-white text-xs font-bold uppercase tracking-wider px-5 py-2.5 rounded-lg transition-all active:scale-[0.98] shadow-md shadow-primary/10"
            >
              Sign In
            </button>
          </div>
        </div>
      </header>

      {/* ── ASYMMETRIC EDITORIAL HERO ── */}
      <section className="bg-bg border-b border-muted/20 py-20 lg:py-28 relative overflow-hidden">
        <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-primary/5 rounded-full blur-3xl pointer-events-none -mr-48 -mt-48" />

        <div className="max-w-7xl mx-auto px-6 grid grid-cols-1 lg:grid-cols-[1.2fr_0.8fr] gap-16 items-center">
          {/* Left Column: Bold Typography */}
          <div className="text-left space-y-6">
            <h2 className="text-4xl sm:text-6xl font-black text-dark tracking-tight leading-[1.05]">
              Evaluation, <br />
              <span className="text-primary">Recalculated.</span>
            </h2>

            <p className="text-text/60 text-base sm:text-lg max-w-xl leading-relaxed font-medium">
              Evolving capstone evaluation beyond global templates. EvalSys delivers secure instructor controls, automated multi-panel scoring, and alphabetized record exports scoped directly by subject.
            </p>

            <div className="pt-4 flex flex-col sm:flex-row items-stretch sm:items-center gap-4">
              <button
                onClick={() => navigate('/login')}
                className="evl-btn-primary py-4 px-8 text-sm uppercase tracking-wider shadow-lg shadow-primary/15 hover:shadow-primary/25 transition-all"
              >
                Instructor & Panel Portal
              </button>
              <button
                onClick={() => setShowStudentModal(true)}
                className="evl-btn-secondary py-4 px-8 text-sm uppercase tracking-wider"
              >
                Register Student Group
              </button>
            </div>

            <p className="text-xs text-text/40">
              Accounts are provisioned exclusively by administration.{' '}
              <button onClick={() => setShowAccountModal(true)} className="text-primary font-bold hover:underline">
                Request an Account.
              </button>
            </p>
          </div>

          {/* Right Column: Real Evaluation Sheet Preview */}
          <div className="evl-card bg-surface shadow-xl border border-muted/50 overflow-hidden">
            {/* Sheet Header */}
            <div className="px-5 py-3 border-b border-muted/30 flex items-center justify-between bg-bg/60">
              <div className="min-w-0">
                <p className="text-[9px] font-mono text-text/40 uppercase tracking-widest">Grading Rubric in Use</p>
                <p className="text-xs font-extrabold text-dark truncate">Integrative Presentation Rubrics</p>
              </div>
              <div className="text-right shrink-0 ml-4">
                <p className="text-[9px] font-mono text-text/40 uppercase tracking-widest">Current Total</p>
                <p className="text-2xl font-black text-dark font-mono leading-none">86<span className="text-xs font-bold text-text/30">/100</span></p>
                <span className="text-[9px] font-mono font-black text-success bg-success/10 px-1.5 py-0.5 rounded mt-1 inline-block">SUBMITTED</span>
              </div>
            </div>

            {/* Rubric Criteria Rows */}
            <div className="divide-y divide-muted/20">
              {[
                { label: '1. System Functionality', max: 25, score: 25, level: 'Excellent', color: 'text-success' },
                { label: '2. API Integration',       max: 25, score: 25, level: 'Excellent', color: 'text-success' },
                { label: '3. Presentation & Demo',   max: 15, score: 12, level: 'Good',      color: 'text-primary' },
                { label: '4. UI / UX Design',        max: 10, score: 9,  level: 'Excellent', color: 'text-success' },
                { label: '5. Q & A',                 max: 25, score: 15, level: 'Fair',      color: 'text-warning' },
              ].map((row) => (
                <div key={row.label} className="px-5 py-3">
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-[11px] font-bold text-dark">{row.label}</span>
                    <span className={`text-[9px] font-black uppercase tracking-widest ${row.color}`}>{row.level}</span>
                  </div>
                  {/* Level pill row */}
                  <div className="grid grid-cols-4 gap-1 mb-2">
                    {['Excellent', 'Good', 'Fair', 'Poor'].map((lvl) => (
                      <div key={lvl} className={`h-5 rounded text-[8px] font-bold flex items-center justify-center ${
                        lvl === row.level
                          ? lvl === 'Excellent' ? 'bg-success/15 text-success'
                          : lvl === 'Good'      ? 'bg-primary/15 text-primary'
                          : lvl === 'Fair'      ? 'bg-warning/15 text-warning'
                          : 'bg-danger/15 text-danger'
                          : 'bg-muted/20 text-text/30'
                      }`}>
                        {lvl}
                      </div>
                    ))}
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-[9px] text-text/30 font-mono">Max: {row.max} pts</span>
                    <span className="text-sm font-black text-dark font-mono">{row.score}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ── FEATURES: NON-STANDARD LAYOUT ── */}
      <section className="bg-white border-b border-muted/20">

        {/* INSTRUCTOR — dense feature index table */}
        <div className="max-w-7xl mx-auto px-6 pt-20 pb-16">
          <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-6 mb-10">
            <div>
              <span className="text-[10px] font-mono text-primary uppercase tracking-widest font-black">
                Instructor Controls
              </span>
              <h3 className="text-2xl sm:text-3xl font-black text-dark mt-1 tracking-tight">
                Everything you need to run an evaluation.
              </h3>
            </div>
            <p className="text-text/45 text-xs max-w-xs leading-relaxed">
              Full-scope administration from subject creation, through grading, to final export — all in one unified dashboard.
            </p>
          </div>

          {/* Feature Index — row list, not cards */}
          <div className="divide-y divide-muted/30 border-t border-muted/30">
            {[
              { tag: 'BLOCKS',  label: 'Block & Section Management',    desc: 'Create and manage evaluation blocks per subject. Each block holds its own groups, assigned panels, and results in complete isolation.' },
              { tag: 'GROUPS',  label: 'Student Group Manager',          desc: 'Register and edit groups with structured member names — Last, First, Middle — with duplicate detection and bulk CSV import.' },
              { tag: 'ASSIGN',  label: 'Panel-to-Block Assignment',      desc: 'Bulk-assign panel judges to entire blocks rather than individual groups, cutting setup time dramatically.' },
              { tag: 'IMPORT',  label: 'Bulk CSV Importing',             desc: 'Upload 100+ student groups or panel accounts instantly via downloadable spreadsheet templates.' },
              { tag: 'RUBRIC',  label: 'Dynamic Rubric Builder',         desc: 'Craft custom evaluation rubrics with adjustable criteria, score levels, and maximum point allocations — one active rubric per subject.' },
              { tag: 'ACCESS',  label: 'Expiring Registration Links',    desc: 'Generate token-protected enrollment links per block with automatic date and time expiration. Direct public registration is disabled.' },
              { tag: 'RESULTS', label: 'Averaged Results & Score Clear', desc: 'View per-block averaged scores computed across all assigned panels. Instructors can clear individual panel scores to allow re-grading.' },
              { tag: 'EXPORT',  label: 'CSV Grade Exports',              desc: 'Download per-block or system-wide CSVs with group scores, panel attribution, missing evaluators, and qualitative comments.' },
              { tag: 'LOCK',    label: 'Global Grading Lock',            desc: 'Freeze all active score submissions across the platform in a single toggle click the moment presentations end.' },
              { tag: 'RESET',   label: 'Scoped Master Reset',            desc: 'Wipe evaluations, groups, and blocks for a selected subject or globally — accounts and rubrics are always preserved.' },
            ].map((item) => (
              <div key={item.tag} className="grid grid-cols-[64px_1fr_2fr] lg:grid-cols-[80px_280px_1fr] gap-4 lg:gap-8 items-center py-4 hover:bg-bg/60 transition-colors px-2 -mx-2 rounded-lg group">
                <span className="text-[9px] font-mono font-black text-primary/60 uppercase tracking-widest group-hover:text-primary transition-colors">
                  {item.tag}
                </span>
                <span className="font-bold text-sm text-dark">{item.label}</span>
                <span className="text-xs text-text/50 leading-relaxed hidden sm:block">{item.desc}</span>
              </div>
            ))}
          </div>
        </div>

        {/* PANEL JUDGES — dark asymmetric strip */}
        <div className="bg-dark text-white">
          <div className="max-w-7xl mx-auto px-6 py-16 grid grid-cols-1 lg:grid-cols-[320px_1fr] gap-10 lg:gap-20">
            <div className="border-b lg:border-b-0 lg:border-r border-white/10 pb-8 lg:pb-0 lg:pr-16">
              <span className="text-[10px] font-mono text-success uppercase tracking-widest font-black block mb-3">
                Panel Judge Workspace
              </span>
              <h3 className="text-2xl font-black text-white tracking-tight leading-tight">
                Built for <br/>live grading<br/>under pressure.
              </h3>
              <p className="text-white/45 text-xs mt-4 leading-relaxed">
                Runs cleanly on any screen. Automatically recovers if the internet drops mid-session.
              </p>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-10 gap-y-8">
              {[
                { label: 'Digital Score Sheets', desc: 'Forms render active subject rubrics. Full score validation before any submission is permitted.' },
                { label: 'Qualitative Comments', desc: 'Textual feedback fields allow judges to leave remarks alongside numerical scores.' },
                { label: 'Works Offline, Saves Automatically', desc: 'If the internet suddenly drops mid-session, the system keeps running and continues saving scores locally. Nothing is lost — all progress is restored the moment reconnection happens.' },
                { label: 'Print Offline Worksheet', desc: 'One-click printable rubric sheet for grading manually when local network access is unavailable.' },
              ].map((item, i) => (
                <div key={i} className="flex gap-4 items-start">
                  <span className="text-success text-xs font-mono font-black mt-0.5 shrink-0">
                    {String(i + 1).padStart(2, '0')}
                  </span>
                  <div>
                    <h5 className="font-extrabold text-sm text-white mb-1">{item.label}</h5>
                    <p className="text-xs text-white/45 leading-relaxed">{item.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

      </section>

      {/* ── DUAL-COLUMN FAQ SECTION ── */}
      <section className="bg-bg border-t border-b border-muted/20 py-20 lg:py-28">
        <div className="max-w-7xl mx-auto px-6 grid grid-cols-1 lg:grid-cols-[0.8fr_1.2fr] gap-12">
          
          <div>
            <span className="text-[10px] font-mono text-primary uppercase tracking-widest font-black block mb-2">
              [ FAQ ]
            </span>
            <h3 className="text-2xl sm:text-3xl font-black text-dark uppercase tracking-wide">
              Got Questions?
            </h3>
            <p className="text-text/50 text-xs mt-3 leading-relaxed max-w-sm">
              We have compiled critical workflow information to ensure instructors and judges start grading presentations immediately.
            </p>
            <div className="mt-8 p-5 rounded-xl border border-muted bg-white">
              <p className="text-xs font-bold text-dark mb-1 uppercase tracking-wider">Account Request</p>
              <p className="text-[11px] text-text/60 leading-relaxed">
                All credentials must be generated by administrators. Please email us at:
              </p>
              <span className="block font-black text-sm text-primary mt-2 select-all font-mono">
                garciajerico217@gmail.com
              </span>
            </div>
          </div>

          <div className="space-y-4">
            {faqs.map((faq, index) => {
              const active = activeFaq === index;
              return (
                <div key={index} className="evl-card bg-surface overflow-hidden">
                  <button
                    onClick={() => toggleFaq(index)}
                    className="w-full px-6 py-4 text-left flex justify-between items-center gap-4 hover:bg-bg/40 transition-all"
                  >
                    <span className="font-bold text-sm text-dark">{faq.q}</span>
                    <span className="text-text/40 text-xs font-mono font-bold">{active ? '[-]' : '[+]'}</span>
                  </button>
                  {active && (
                    <div className="px-6 pb-5 pt-1 border-t border-muted/10 text-xs text-text/60 leading-relaxed bg-bg/10">
                      {faq.a}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* ── FOOTER ── */}
      <footer className="bg-dark text-white py-16 border-t border-white/5">
        <div className="max-w-7xl mx-auto px-6 flex flex-col md:flex-row items-center justify-between gap-8">
          <div className="flex items-center gap-4">
            <div className="w-10 h-10 rounded-xl bg-primary/20 flex items-center justify-center text-primary text-base font-black shrink-0">
              E
            </div>
            <div>
              <p className="text-sm font-black uppercase tracking-wider">EvalSys Platform</p>
              <p className="text-[10px] text-white/40 font-mono">Automated rubric evaluations and multi-tenant grading.</p>
            </div>
          </div>

          <div className="text-center md:text-right space-y-1">
            <p className="text-white/20 text-[9px] font-bold uppercase tracking-widest">
              Developed & Maintained by
            </p>
            <p className="text-base font-black text-white/80">Jerico B. Garcia</p>
            <p className="text-xs text-primary font-bold font-mono">garciajerico217@gmail.com</p>
          </div>
        </div>
      </footer>

      {/* ── STUDENT MODAL ── */}
      {showStudentModal && (
        <div className="fixed inset-0 bg-dark/60 backdrop-blur-sm flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-xl shadow-2xl border border-muted max-w-md w-full p-6 relative">
            <button
              onClick={() => setShowStudentModal(false)}
              className="absolute right-4 top-4 text-text/40 hover:text-text font-bold text-sm"
            >
              ✕
            </button>
            <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center text-primary text-xl font-bold mb-4">
              🎓
            </div>
            <h4 className="text-lg font-black text-dark">Student Group Registration</h4>
            <p className="text-xs text-text/50 leading-relaxed mt-2">
              To prevent duplicate submissions, public registrations require unique token links generated by instructors.
            </p>
            <p className="text-xs text-text/60 leading-relaxed mt-4 font-semibold p-4 bg-primary/5 border border-primary/20 rounded-lg">
              Check your class group or email for an instructor-generated link resembling: <code className="text-primary font-mono text-[10px]">/register?token=...</code>
            </p>
            <p className="text-xs text-text/50 leading-relaxed mt-4">
              Please contact your subject instructor directly if you have not received your block registration token.
            </p>
            <button
              onClick={() => setShowStudentModal(false)}
              className="evl-btn-primary w-full mt-6 py-3 text-xs uppercase tracking-wider"
            >
              Understood
            </button>
          </div>
        </div>
      )}

      {/* ── ACCOUNT CREATION MODAL ── */}
      {showAccountModal && (
        <div className="fixed inset-0 bg-dark/60 backdrop-blur-sm flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-xl shadow-2xl border border-muted max-w-md w-full p-6 relative">
            <button
              onClick={() => setShowAccountModal(false)}
              className="absolute right-4 top-4 text-text/40 hover:text-text font-bold text-sm"
            >
              ✕
            </button>
            <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center text-primary text-xl font-bold mb-4">
              ✉
            </div>
            <h4 className="text-lg font-black text-dark">Portal Access Request</h4>
            <p className="text-xs text-text/50 leading-relaxed mt-2">
              For complete security, public registration of Instructor or Panel Judge accounts is deactivated.
            </p>
            <p className="text-xs text-text/60 leading-relaxed mt-4 font-semibold p-4 bg-success/5 border border-success/20 rounded-lg text-success">
              To request a new administrator or judge account, please contact us via email at:
              <span className="block font-black text-sm mt-1.5 select-all font-mono text-dark bg-white py-2 px-3 border border-muted/50 rounded text-center">
                garciajerico217@gmail.com
              </span>
            </p>
            <p className="text-xs text-text/50 leading-relaxed mt-4">
              Be sure to provide your full name, academic department, and subject areas.
            </p>
            <button
              onClick={() => setShowAccountModal(false)}
              className="evl-btn-primary w-full mt-6 py-3 text-xs uppercase tracking-wider"
            >
              Close
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
